#pragma once
#include "classes_all.h"

struct cls_0x431750 {
    dword mbr_0x0;// offset 00 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x4;// offset 04 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x8;// offset 08 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0xc;// offset 0c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x10;// offset 10 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x14;// offset 14 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x18;// offset 18 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x20;// offset 20 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x24;// offset 24 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x28;// offset 28 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x2c;// offset 2c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x30;// offset 30 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x34;// offset 34 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x38;// offset 38 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x3c;// offset 3c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x40;// offset 40 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x44;// offset 44 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x48;// offset 48 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x4c;// offset 4c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x50;// offset 50 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x54;// offset 54 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    byte mbr_0x58;// offset 58 - 1 bytes - Unsigned Byte (db)
    byte mbr_0x59;// offset 59 - 1 bytes - Unsigned Byte (db)
    byte mbr_0x5a;// offset 5a - 1 bytes - Unsigned Byte (db)
    byte mbr_0x5c;// offset 5c - 1 bytes - Unsigned Byte (db)
    byte mbr_0x5d;// offset 5d - 1 bytes - Unsigned Byte (db)
    byte mbr_0x5e;// offset 5e - 1 bytes - Unsigned Byte (db)
    dword mbr_0x60;// offset 60 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x64;// offset 64 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x68;// offset 68 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x6c;// offset 6c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x70;// offset 70 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x74;// offset 74 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x78;// offset 78 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x7c;// offset 7c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x80;// offset 80 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x84;// offset 84 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x88;// offset 88 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x8c;// offset 8c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)

    undefined4 meth_0x431750(cls_0x431750 *param_1, int *param_2);
};
