#pragma once
#include "classes_all.h"

struct cls_0x5a3544 {
    dword mbr_0x4;// offset 04 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x8;// offset 08 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0xc;// offset 0c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x10;// offset 10 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x14;// offset 14 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x18;// offset 18 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x1c;// offset 1c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x20;// offset 20 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x28;// offset 28 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x2c;// offset 2c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x30;// offset 30 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x34;// offset 34 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x38;// offset 38 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x3c;// offset 3c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x40;// offset 40 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x44;// offset 44 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x48;// offset 48 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x4c;// offset 4c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x50;// offset 50 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x54;// offset 54 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x58;// offset 58 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x5c;// offset 5c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x60;// offset 60 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x64;// offset 64 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x68;// offset 68 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x6c;// offset 6c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x70;// offset 70 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x74;// offset 74 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x90;// offset 90 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x94;// offset 94 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x98;// offset 98 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x9c;// offset 9c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0xa4;// offset a4 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0xa8;// offset a8 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0xac;// offset ac - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0xb0;// offset b0 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0xb4;// offset b4 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0xb8;// offset b8 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0xbc;// offset bc - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0xc0;// offset c0 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0xc4;// offset c4 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0xc8;// offset c8 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0xcc;// offset cc - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0xf0;// offset f0 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0xf4;// offset f4 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0xf8;// offset f8 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0xfc;// offset fc - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x100;// offset 100 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x104;// offset 104 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x108;// offset 108 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x10c;// offset 10c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x110;// offset 110 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x114;// offset 114 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x118;// offset 118 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x11c;// offset 11c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x120;// offset 120 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x124;// offset 124 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x128;// offset 128 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x12c;// offset 12c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x130;// offset 130 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x134;// offset 134 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x138;// offset 138 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x13c;// offset 13c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x140;// offset 140 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x144;// offset 144 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x148;// offset 148 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x14c;// offset 14c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x150;// offset 150 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x154;// offset 154 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x158;// offset 158 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x15c;// offset 15c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x160;// offset 160 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x164;// offset 164 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x168;// offset 168 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x16c;// offset 16c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x170;// offset 170 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x174;// offset 174 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x178;// offset 178 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x188;// offset 188 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)

    virtual void virt_meth_0x401900();
    virtual void virt_meth_0x4036a0();
    virtual void virt_meth_0x404270();
    virtual undefined4 virt_meth_0x405770(byte *param_1);
    virtual cls_0x5a3544 * virt_meth_0x405a80();
    virtual cls_0x5a3544 * virt_meth_0x405d20();
    virtual cls_0x5a3544 * virt_meth_0x405ec0();
    virtual cls_0x5a3544 * virt_meth_0x405fe0();
    virtual void virt_meth_0x40db50();
};
