#pragma once
#include "classes_all.h"

struct cls_0x5a8aa4 {
    dword mbr_0x4;// offset 04 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x8;// offset 08 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0xc;// offset 0c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x14;// offset 14 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    byte mbr_0x3c;// offset 3c - 1 bytes - Unsigned Byte (db)
    dword mbr_0x9c;// offset 9c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0xac;// offset ac - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0xec;// offset ec - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0xfc;// offset fc - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x100;// offset 100 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x108;// offset 108 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x10c;// offset 10c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x110;// offset 110 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x114;// offset 114 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x118;// offset 118 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x11c;// offset 11c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x120;// offset 120 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x124;// offset 124 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x128;// offset 128 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x12c;// offset 12c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x134;// offset 134 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x138;// offset 138 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x13c;// offset 13c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x140;// offset 140 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x148;// offset 148 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x14c;// offset 14c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x150;// offset 150 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x154;// offset 154 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x15c;// offset 15c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x160;// offset 160 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x164;// offset 164 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x168;// offset 168 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x174;// offset 174 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x178;// offset 178 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x17c;// offset 17c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x180;// offset 180 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x184;// offset 184 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x188;// offset 188 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x18c;// offset 18c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x190;// offset 190 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x194;// offset 194 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x198;// offset 198 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x19c;// offset 19c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x1a0;// offset 1a0 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x3034;// offset 3034 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x3038;// offset 3038 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x303c;// offset 303c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x3040;// offset 3040 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x3044;// offset 3044 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)

    virtual cls_0x5a8aa4 * virt_meth_0x4f4da0();
    virtual TScreen * virt_meth_0x4f4e10(int param_1);
};
