#pragma once
#include "classes_all.h"

struct cls_0x5a8f20 {
    dword mbr_0x4;// offset 04 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x8;// offset 08 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0xc;// offset 0c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x14;// offset 14 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    byte mbr_0x3c;// offset 3c - 1 bytes - Unsigned Byte (db)
    dword mbr_0x9c;// offset 9c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0xac;// offset ac - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0xd8;// offset d8 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0xec;// offset ec - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0xfc;// offset fc - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x100;// offset 100 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x104;// offset 104 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x108;// offset 108 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x10c;// offset 10c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x110;// offset 110 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x114;// offset 114 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x124;// offset 124 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x128;// offset 128 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x12c;// offset 12c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x130;// offset 130 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x134;// offset 134 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x138;// offset 138 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x148;// offset 148 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x14c;// offset 14c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x184;// offset 184 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x1b40;// offset 1b40 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x1b48;// offset 1b48 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x1b4c;// offset 1b4c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x1b50;// offset 1b50 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x1b64;// offset 1b64 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x1b68;// offset 1b68 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x1b6c;// offset 1b6c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x1b70;// offset 1b70 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x1b74;// offset 1b74 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x1b78;// offset 1b78 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x1b7c;// offset 1b7c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x1b80;// offset 1b80 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x1b84;// offset 1b84 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x1b8c;// offset 1b8c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x1b90;// offset 1b90 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x1ce4;// offset 1ce4 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x1ce8;// offset 1ce8 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x1cf0;// offset 1cf0 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)

    virtual cls_0x5a8f20 * virt_meth_0x4f4fb0();
    virtual cls_0x5a47f0 * virt_meth_0x4f4fe0();
    virtual cls_0x5a8f20 * virt_meth_0x4f5080();
};
