#pragma once
#include "classes_all.h"

struct cls_0x48b690 {
    dword mbr_0x0;// offset 00 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x4;// offset 04 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x8;// offset 08 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x14;// offset 14 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x18;// offset 18 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x1c;// offset 1c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x28;// offset 28 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x2c;// offset 2c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x30;// offset 30 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x3c;// offset 3c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x40;// offset 40 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x44;// offset 44 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x50;// offset 50 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x54;// offset 54 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x58;// offset 58 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x5c;// offset 5c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x60;// offset 60 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x64;// offset 64 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x68;// offset 68 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x6c;// offset 6c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x70;// offset 70 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x74;// offset 74 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x78;// offset 78 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x7c;// offset 7c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x80;// offset 80 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x84;// offset 84 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x88;// offset 88 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x8c;// offset 8c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x90;// offset 90 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x94;// offset 94 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x98;// offset 98 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x9c;// offset 9c - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0xa0;// offset a0 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0xa4;// offset a4 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0xa8;// offset a8 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0xac;// offset ac - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0xd0;// offset d0 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0xd4;// offset d4 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0xd8;// offset d8 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0xdc;// offset dc - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0xe0;// offset e0 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0xe4;// offset e4 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0xe8;// offset e8 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0xec;// offset ec - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0xf0;// offset f0 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0xf4;// offset f4 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x164;// offset 164 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x168;// offset 168 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x1dc;// offset 1dc - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)
    dword mbr_0x1e0;// offset 1e0 - 4 bytes - Unsigned Double-Word (ddw, 4-bytes)

    undefined4 meth_0x48b690();
    undefined4 meth_0x48b990();
};
