#!/usr/bin/env python3
"""Freeze exact retail ID -> existing preview candidates from the source ledger."""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def generate(ledger):
    raw = ledger.read_bytes()
    rows = json.loads(raw)['retail_effects']
    lines = ['// Generated by tools/vfx/generate_review_preview_map.py; do not infer aliases.',
             '// Ledger SHA-256: ' + hashlib.sha256(raw).hexdigest()]
    for row in sorted(rows, key=lambda r: int(r['retail_type_id'], 16)):
        candidates = [name for name in row['preview_candidates']
                      if not any(tag in name.upper() for tag in ('_SHIM', '_DIAGNOSTIC', 'EDITOR_DEFAULT', '.ONHAND'))
                      and not name.endswith('_AB')]
        candidates.sort(key=lambda name: (0 if '_AUTHORED_' in name else 1 if '_BESPOKE' in name.upper() else 2))
        for name in dict.fromkeys(candidates):
            lines.append('{' + row['retail_type_id'] + 'u, ' + json.dumps(name) + '}, // ' + row['retail_name'])
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--ledger', type=Path, default=ROOT/'docs/vfx/EFFECT_BURNDOWN.json')
    p.add_argument('--output', type=Path, default=ROOT/'src/vfxreviewpreviewmap.inc')
    p.add_argument('--check', action='store_true')
    a = p.parse_args(); result = generate(a.ledger)
    if a.check:
        if a.output.read_text() != result:
            raise SystemExit('Review preview mapping differs from source ledger')
    else:
        a.output.write_text(result)
