// *************************************************************************
// *                         Cinematix Revenant                            *
// *                  Revenant Revisited (port) - 2026                     *
// *                  playscreen.h - main play-mode screen                 *
// *************************************************************************
//
// TPlayScreen drives an in-game session: world rendering through the
// owned TMapRenderer, command/input dispatch, game-time tracking, and
// pane composition for HUD / inventory / editor / dialogs.
//
// Architecture:
//   - World rendering happens via the same TMapRenderer that powers
//     --test=sector (see docs/RENDERER_ARCHITECTURE.md). The main frame
//     loop calls RenderFrame() each tick; panes composite 2D on top.
//   - Game-time + time-of-day live here so other systems (lighting,
//     save-game, scripts) can ask the screen for "now".
//   - Save-load entry points stage their work and run on the next
//     Update() so we don't tear down state mid-frame.
//
// The retail TPlayScreen and its DrawBackground / Pulse / Animate /
// post-character anim arrays have been retired to attic/src/playscreen.*
// (see that file for the legacy implementation if a particular helper
// needs to be revived).
//
// *************************************************************************

#pragma once

#include "revenant.h"

#include "graphics.h"
#include "screen.h"

#include <memory>

class TMapRenderer;
class TObjectImagery;

// Game control commands generated by mouse, keyboard, and joystick.
enum GAMECOMMAND : int32_t
{
    GAMECMD_NONE = 0,
    GAMECMD_COMBAT, GAMECMD_BOW, GAMECMD_FULLSCREEN,
    GAMECMD_USE, GAMECMD_GET, GAMECMD_JUMP,
    GAMECMD_WALKACTION1, GAMECMD_WALKACTION2, GAMECMD_WALKACTION3,
    GAMECMD_INVENTORY,
    GAMECMD_INVOKE1, GAMECMD_INVOKE2, GAMECMD_INVOKE3, GAMECMD_INVOKE4,
    GAMECMD_INVUSE, GAMECMD_INVMOVE, GAMECMD_INVDROP, GAMECMD_INVEXIT,
    GAMECMD_SWING, GAMECMD_THRUST, GAMECMD_CHOP,
    GAMECMD_COMBO1, GAMECMD_COMBO2, GAMECMD_COMBO3,
    GAMECMD_COMBO4, GAMECMD_COMBO5, GAMECMD_COMBO6,
    GAMECMD_COMBO7, GAMECMD_COMBO8, GAMECMD_COMBO9,
    GAMECMD_COMBO10, GAMECMD_COMBO11, GAMECMD_COMBO12,
    GAMECMD_DODGE,
    GAMECMD_COMBATACTION1, GAMECMD_COMBATACTION2, GAMECMD_COMBATACTION3,
    GAMECMD_BOWAIM, GAMECMD_BOWSHOOT,
    GAMECMD_BOWACTION1, GAMECMD_BOWACTION2, GAMECMD_BOWACTION3,
    GAMECMD_SNEAKATTACK1, GAMECMD_SNEAKATTACK2, GAMECMD_SNEAKATTACK3,
    GAMECMD_SNEAKACTION1, GAMECMD_SNEAKACTION2, GAMECMD_SNEAKACTION3,
    GAMECMD_DIRDOWN, GAMECMD_DIRUP,
    GAMECMD_MOVEDOWN, GAMECMD_MOVEUP,
    GAMECMD_LEAPDOWN, GAMECMD_LEAPUP,
    GAMECMD_BLOCKDOWN, GAMECMD_BLOCKUP,
};

// CMDFLAG_* bitmask values fed into TPlayer command-flag state.
#define CMDFLAG_UPRIGHT     (1<<0)
#define CMDFLAG_RIGHT       (1<<1)
#define CMDFLAG_DOWNRIGHT   (1<<2)
#define CMDFLAG_DOWN        (1<<3)
#define CMDFLAG_DOWNLEFT    (1<<4)
#define CMDFLAG_LEFT        (1<<5)
#define CMDFLAG_UPLEFT      (1<<6)
#define CMDFLAG_UP          (1<<7)
#define CMDFLAG_RUN         (1<<8)
#define CMDFLAG_SNEAK       (1<<9)
#define CMDFLAG_LEAP        (1<<10)
#define CMDFLAG_BLOCK       (1<<11)

#define CMDFLAG_DIRFLAGS    (0xFF)
#define CMDFLAG_MOVEFLAGS   (0x300)

// Coarse time-of-day bucket from gametime, used by lighting and a few
// scripted hooks.
enum
{
    DAY_MIDNIGHT = 0,
    DAY_MORNING,
    DAY_DAYTIME,
    DAY_NOON,
    DAY_EVENING,
    DAY_NIGHT,
};

_CLASSDEF(TPlayScreen)

class TPlayScreen : public TScreen
{
  public:
    TPlayScreen();
    ~TPlayScreen() override;

    // ---- Lifetime ------------------------------------------------------
    bool Initialize() override;
    void Close()      override;

    // Drop a default "Locke" TPlayer into the loaded sector at
    // (level, sx, sy) and register him with PlayerManager. Used when
    // there is no save-load path / new-game flow yet -- gives the
    // world a Player to render and drive. Called from inside the
    // TMapRenderer post-load hook so the renderer's drawable scan
    // picks the player up. Returns true if Player exists after the call.
    bool SpawnDefaultPlayer(int32_t level, int32_t sector_x, int32_t sector_y);

    // ---- Per-frame -----------------------------------------------------
    // Update() advances game state (world, characters, input). It does NO
    // GPU work. The main frame loop calls RenderFrame() afterwards to
    // drive TMapRenderer; panes then composite 2D on top in Draw().
    void Update();
    void RenderFrame();

    // Legacy entry points kept so existing callers compile. Pulse() /
    // Animate() forward to Update() in the new model; DrawBackground() is
    // now a no-op (no BITMAP.100 backdrop). Treat them as deprecated.
    virtual void Pulse();
    virtual void Animate(bool draw);
    virtual void DrawBackground();

    // ---- Input ---------------------------------------------------------
    void MouseClick(int32_t button, int32_t x, int32_t y) override;
    void MouseMove (int32_t button, int32_t x, int32_t y) override;
    void KeyPress  (int32_t key, bool down)               override;
    virtual void Joystick(int32_t key, bool down);
    virtual void Command (GAMECOMMAND command);

    // ---- Mode flags ----------------------------------------------------
    [[nodiscard]] bool IsFullScreen() const { return fullscreen; }
    void               SetFullScreen(bool on);

    [[nodiscard]] bool IsDemoMode() const { return demomode; }
    void               SetDemoMode(bool on);

    [[nodiscard]] bool IsControlOn() const { return controlon; }
    void               SetControlOn(bool on);

    void MultiUpdate() { multidirty = true; }
      // Marks the multipane-overhang region dirty so the next composite
      // refreshes it.

    void SetNextPane(PTPane pane) { nextpane = pane; }
      // Defers a pane-add to the start of the next Update().

    void HideLowerPanes();
    void ShowLowerPanes();

    // ---- Save / load ---------------------------------------------------
    [[nodiscard]] int32_t GameNum() const { return gamenum; }
    void LoadGame    (int32_t game);
    void LoadGameFile(const char* path);
    void SaveGame    (int32_t game);
    void NewGame() { LoadGame(0); }
    void SaveMap();

    // ---- Game time -----------------------------------------------------
    [[nodiscard]] int32_t GameFrame()    const;
    [[nodiscard]] int32_t GameTime()     const { return gametime; }
    void                   SetGameTime(int32_t t);
    [[nodiscard]] int32_t TimeOfDay()    const;
    [[nodiscard]] int32_t Daylight()     const;
    [[nodiscard]] int32_t DayTimeFlag()  const;

    // ---- Post-character overlays --------------------------------------
    // Overlay primitives queued by gameplay code (spell sparkles, damage
    // numbers, dialog text floating over heads). The new render path
    // composites these as part of the post-world UI step. Provided as
    // no-ops on the new path until the overlay pipeline is wired.
    void AddPostCharAnim(int32_t x, int32_t y, int32_t z,
                         PTBitmap bm, uint32_t drawmode, int32_t dim = 0);
    void AddPostCharText(char* text, int32_t x, int32_t y,
                         PSColor color, int32_t wrapwidth);

    // ---- Legacy hooks kept to satisfy existing callers -----------------
    void CreateBackgroundAreas();
    void DrawOverhangs(bool temporary = false);

    // ---- Map / world access -------------------------------------------
    // Borrowed pointer to the owned map renderer. Null before Initialize()
    // and after Close().
    [[nodiscard]] TMapRenderer* MapRenderer() const { return mapRenderer.get(); }

    // ---- TScreen pulse-driver hook -------------------------------------
    static TScreen* ShowScreen(TScreen* screen, int32_t ticks);

    void UpdateMove();
      // Drives TPlayer movement from the current command-flag state.
      // Called from TGameMode::Tick each frame; public so the runtime
      // mode can drive it without befriending the screen.

  private:

    std::unique_ptr<TMapRenderer> mapRenderer;

    // Mode flags
    bool fullscreen   = false;
    bool demomode     = false;
    bool controlon    = true;
    bool interfacedirty = false;
    bool multidirty   = false;

    // Save / load deferred work
    bool    loadgame  = false;
    bool    savegame  = false;
    int32_t gamenum   = 0;
    char    loadgamepath[MAXPATHLEN] = {};
    bool    savemap   = false;

    // Game time
    int32_t gameframes        = 0;  // frames since this PlayScreen started
    int32_t sessionstart      = 0;  // frame count at last SetGameTime
    int32_t lastsessionframes = 0;  // total frames in previous game session
    int32_t gametime          = 0;  // hundredths of a second, in-game
    int32_t timeofday         = 0;  // game minutes

    // Pane plumbing
    PTPane nextpane = nullptr;

    // Effect imagery cached at boot (blood, sparks). Optional; kept null
    // when the imagery isn't in the current data set.
    TObjectImagery* bloodimagery  = nullptr;
    TObjectImagery* sparksimagery = nullptr;
};

// Helpers used by save-game + scripting code. Conversion uses the engine's
// fixed game-frame rate (see playscreen.cpp).
int32_t ConvertFramesToMinutes(int32_t frames);
int32_t ConvertMinutesToFrames(int32_t minutes);
