// *************************************************************************
// *                         Cinematix Revenant                            *
// *                  Revenant Revisited (port) - 2026                     *
// *                  playscreen.h - main play-mode screen                 *
// *************************************************************************
//
// TPlayScreen presents the game in progress: world rendering through the
// owned TMapRenderer, command/input dispatch, game-time tracking, and
// pane composition for HUD / inventory / editor / dialogs. The world itself
// (map, players, areas, game states) belongs to the game session
// (TGameSession, owned by TGameFlow); the screen binds to it.
//
// Architecture:
//   - World rendering happens via the same TMapRenderer that powers
//     --test=sector (see docs/RENDERER_ARCHITECTURE.md). The main frame
//     loop calls RenderFrame() each tick; panes composite 2D on top.
//   - Game-time + time-of-day live here so other systems (lighting,
//     save-game, scripts) can ask the screen for "now".
//   - Save/load requests made during play are queued on the session and
//     carried out at the start of the next Update().
//
// The retail TPlayScreen and its DrawBackground / Pulse / Animate /
// post-character anim arrays have been retired to attic/src/playscreen.*
// (see that file for the legacy implementation if a particular helper
// needs to be revived).
//
// *************************************************************************

#pragma once

#include "revenant.h"

#include "graphics.h"
#include "screen.h"

#include "mapmanager.h"
#include "moviepane.h"

#include <memory>
#include <vector>

class TInGameMenu;
class TMapRenderer;
class TObjectImagery;
class TBottomBarPane;
class TPlyrStatusBar;

// Game control commands generated by mouse, keyboard, and joystick.
enum GAMECOMMAND : int32_t
{
    GAMECMD_NONE = 0,
    GAMECMD_COMBAT, GAMECMD_BOW, GAMECMD_FULLSCREEN,
    GAMECMD_SIDEPANEL, GAMECMD_BOTTOMPANEL,
    GAMECMD_USE, GAMECMD_GET, GAMECMD_JUMP,
    GAMECMD_WALKACTION1, GAMECMD_WALKACTION2, GAMECMD_WALKACTION3,
    GAMECMD_INVENTORY,
    GAMECMD_INVOKE1, GAMECMD_INVOKE2, GAMECMD_INVOKE3, GAMECMD_INVOKE4,
    GAMECMD_INVUSE, GAMECMD_INVMOVE, GAMECMD_INVDROP, GAMECMD_INVEXIT,
    GAMECMD_SWING, GAMECMD_THRUST, GAMECMD_CHOP,
    GAMECMD_COMBO1, GAMECMD_COMBO2, GAMECMD_COMBO3,
    GAMECMD_COMBO4, GAMECMD_COMBO5, GAMECMD_COMBO6,
    GAMECMD_COMBO7, GAMECMD_COMBO8, GAMECMD_COMBO9,
    GAMECMD_COMBO10, GAMECMD_COMBO11, GAMECMD_COMBO12,
    GAMECMD_DODGE,
    GAMECMD_COMBATACTION1, GAMECMD_COMBATACTION2, GAMECMD_COMBATACTION3,
    GAMECMD_BOWAIM, GAMECMD_BOWSHOOT,
    GAMECMD_BOWACTION1, GAMECMD_BOWACTION2, GAMECMD_BOWACTION3,
    GAMECMD_SNEAKATTACK1, GAMECMD_SNEAKATTACK2, GAMECMD_SNEAKATTACK3,
    GAMECMD_SNEAKACTION1, GAMECMD_SNEAKACTION2, GAMECMD_SNEAKACTION3,
    GAMECMD_DIRDOWN, GAMECMD_DIRUP,
    GAMECMD_MOVEDOWN, GAMECMD_MOVEUP,
    GAMECMD_LEAPDOWN, GAMECMD_LEAPUP,
    GAMECMD_BLOCKDOWN, GAMECMD_BLOCKUP,
    // Retail's last four controls (table 0x005d5500 #65-68, Command
    // 0x0047cf40 cases 0x52-0x55): the in-game dialogs without the menu.
    GAMECMD_GAMEOPTIONS, GAMECMD_LOADGAME, GAMECMD_SAVEGAME, GAMECMD_QUICKSAVE,
};

// CMDFLAG_* bitmask values fed into TPlayer command-flag state.
#define CMDFLAG_UPRIGHT     (1<<0)
#define CMDFLAG_RIGHT       (1<<1)
#define CMDFLAG_DOWNRIGHT   (1<<2)
#define CMDFLAG_DOWN        (1<<3)
#define CMDFLAG_DOWNLEFT    (1<<4)
#define CMDFLAG_LEFT        (1<<5)
#define CMDFLAG_UPLEFT      (1<<6)
#define CMDFLAG_UP          (1<<7)
#define CMDFLAG_RUN         (1<<8)
#define CMDFLAG_SNEAK       (1<<9)
#define CMDFLAG_LEAP        (1<<10)
#define CMDFLAG_BLOCK       (1<<11)

#define CMDFLAG_DIRFLAGS    (0xFF)
#define CMDFLAG_MOVEFLAGS   (0x300)

// Populate the global ControlMap with the default game key bindings (the
// canonical GAMECMD_* table), then the player's bindings from Revenant.ini
// [Controls]. Idempotent-ish: callers that need the bindings before
// TPlayScreen exists (the main-menu Options screen, --test=ui-options) can
// call this so ControlMap.NumControls() is non-zero. TPlayScreen::Initialize
// also calls it. The table lives here because it is keyed on GAMECMD_*.
void InitDefaultControlMap();

// Coarse time-of-day bucket from gametime, used by lighting and a few
// scripted hooks.
enum
{
    DAY_MIDNIGHT = 0,
    DAY_MORNING,
    DAY_DAYTIME,
    DAY_NOON,
    DAY_EVENING,
    DAY_NIGHT,
};

_CLASSDEF(TPlayScreen)

class TPlayScreen : public TScreen
{
  public:
    TPlayScreen();
    ~TPlayScreen() override;

    // ---- Lifetime ------------------------------------------------------
    bool Initialize() override;
    void Close()      override;

    // Editor "Place Here" with no game loaded: drop a default "Locke"
    // TPlayer into the loaded sector at (level, sx, sy) and register him
    // with PlayerManager. Games start from newgame.sav (TGameSession).
    // Returns true if Player exists after the call.
    bool SpawnDefaultPlayer(int32_t level, int32_t sector_x, int32_t sector_y);

    // ---- Per-frame -----------------------------------------------------
    // Update() advances game state (world, characters, input). It does NO
    // GPU work. The main frame loop calls RenderFrame() afterwards to
    // drive TMapRenderer; panes then composite 2D on top in Draw().
    void Update();
    void RenderFrame();

    // Legacy entry points kept so existing callers compile. Pulse() /
    // Animate() forward to Update() in the new model; DrawBackground() is
    // now a no-op (no BITMAP.100 backdrop). Treat them as deprecated.
    void Pulse() override;
    void Animate(bool draw) override;
    void DrawBackground() override;

    // ---- Input ---------------------------------------------------------
    void MouseClick(int32_t button, int32_t x, int32_t y) override;
    void MouseMove (int32_t button, int32_t x, int32_t y) override;
    void KeyPress  (int32_t key, bool down)               override;
    void Joystick  (int32_t key, bool down)               override;
    virtual void Command (GAMECOMMAND command);

    // ---- In-game menu --------------------------------------------------
    // REVSYNC: the ESC case of KeyPress @ 0x0047c630: write the save
    // thumbnail from the frame on screen, then open the in-game menu
    // (0x0047e500) over it.
    void OpenInGameMenu();
    // The in-game menu or one of its dialogs is up.
    [[nodiscard]] bool InGameMenuOpen() const;

    // ---- Mode flags ----------------------------------------------------
    [[nodiscard]] bool IsFullScreen() const { return fullscreen; }
    void               SetFullScreen(bool on);

    [[nodiscard]] bool IsDemoMode() const { return demomode; }
    void               SetDemoMode(bool on);

    [[nodiscard]] bool IsControlOn() const { return controlon; }

    // REVSYNC: playmovie @ 0x00427d80 -- retail stopped the CD music
    // (0x0049a560) and played the movie through its blocking player
    // (0x004bc470), so nothing else moved until it ended. Here the movie is a
    // modal pane and the world doesn't tick while it plays.
    void PlayMovie(const char* path);
    [[nodiscard]] bool PlayingMovie() const { return movieplaying; }
    void               SetControlOn(bool on);

    void MultiUpdate() { multidirty = true; }
      // Marks the multipane-overhang region dirty so the next composite
      // refreshes it.

    void SetNextPane(PTPane pane) { nextpane = pane; }
      // Defers a pane-add to the start of the next Update().

    void HideLowerPanes();
    void ShowLowerPanes();

    // The map view on screen (retail MapPane's rect): what the world renders
    // into, inside the HUD's side and bottom panels.
    void GetMapViewRect(int32_t& x, int32_t& y, int32_t& w, int32_t& h) const;

    // ---- The bottom drawer ---------------------------------------------
    // REVSYNC: PlayScreen +0x6a0..+0x6c4, run by its pulse 0x0047b4d0. The
    // drawer holds one thing at a time: the editor's console (mode 1, not
    // ported), the HUD's bottom bar (mode 2; open while SHudState::
    // bottomBarOpen), or the shop (mode 3, BuySellPane). Opening the shop
    // closes the bottom bar and opens the side panel; closing the shop leaves
    // the drawer closed in mode 2 (BuySellScreen_SPEC §1).
    enum class EDrawer : int32_t { Console = 1, Hud = 2, BuySell = 3 };
    [[nodiscard]] EDrawer Drawer() const { return drawer; }           // 0x0047ed20
    // The height the drawer covers at the bottom of the screen.
    [[nodiscard]] int32_t DrawerHeight() const;
    // +0x6b8: buysellscreen asks for the shop (on), its Exit lets it go
    // (off); the drawer follows on the next pulse.
    void RequestBuySell(bool on) { buysellrequest = on; }
    // REVSYNC: 0x0047ecc0 / 0x0047ece0 -- close the drawer on the next pulse
    // if it is open. Only the shop's mode is closed here; see the definition.
    void CloseDrawer();

    // ---- Game time -----------------------------------------------------
    [[nodiscard]] int32_t GameFrame()    const;
    void SetFixtureState(int32_t frame, bool control, bool demo)
        { gameframes = frame; controlon = control; demomode = demo; }
      // Retail A/B fixtures only (retailab_combat.cpp): the frame count and
      // the control / demo flags as a case sets them, without
      // SetControlOn(false)'s input release
    [[nodiscard]] int32_t GameTime()     const { return gametime; }
    void                   SetGameTime(int32_t t);
    [[nodiscard]] int32_t TimeOfDay()    const;
    [[nodiscard]] int32_t Daylight()     const;
    [[nodiscard]] int32_t DayTimeFlag()  const;

    // ---- Post-character overlays --------------------------------------
    // Overlay primitives queued by gameplay code (spell sparkles, damage
    // numbers, dialog text floating over heads). The new render path
    // composites these as part of the post-world UI step. Provided as
    // no-ops on the new path until the overlay pipeline is wired.
    void AddPostCharAnim(int32_t x, int32_t y, int32_t z,
                         PTBitmap bm, uint32_t drawmode, int32_t dim = 0);
    void AddPostCharText(char* text, int32_t x, int32_t y,
                         PSColor color, int32_t wrapwidth);

    // ---- Legacy hooks kept to satisfy existing callers -----------------
    void CreateBackgroundAreas();
    void DrawOverhangs(bool temporary = false);

    // ---- Map / world access -------------------------------------------
    // Borrowed pointer to the owned map renderer. Null before Initialize()
    // and after Close().
    [[nodiscard]] TMapRenderer* MapRenderer() const { return mapRenderer.get(); }

    // ---- Map input ------------------------------------------------------
    // Whether the map has the pointer at (x, y): no modal holding the mouse,
    // no load, not over the shop or a HUD panel, no HUD drag. The play
    // field's clicks, moves and cursor go to the map pane only then.
    [[nodiscard]] bool MapHasPointer(int32_t x, int32_t y) const;
    // The control map's mode for the player's state (walk, combat, bow,
    // sneak): which binding a key's command comes from.
    [[nodiscard]] uint32_t ControlModeMask() const;

    // ---- TScreen pulse-driver hook -------------------------------------
    static TScreen* ShowScreen(TScreen* screen, int32_t ticks);

    void UpdateMove();
      // Drives TPlayer movement from the current command-flag state.
      // Called from TGameMode::Tick each frame; public so the runtime
      // mode can drive it without befriending the screen.

  private:
    // Points the renderer at MapManager's current map (the session's world).
    void BindWorld();

    // A save loaded during play (TGameSession::Loading). Retail loaded it
    // synchronously, the screen standing still; here the session runs it a
    // step a tick while the world holds, and a still of the world and the
    // HUD panels (the frame's layers under the pane tree, captured as the
    // load began) stands in for them. The panes keep drawing over it.
    // docs/gameflow/forensics/INGAME_MENU.md §5.1.
    void StepGameLoad();
    void FreezeFrame(const uint8_t* rgba, int32_t width, int32_t height);
    void ShowStill();
    void ThawFrame();

    // The drawer half of Pulse 0x0047b4d0.
    void UpdateDrawer();
    void OpenBuySellDrawer();
    void CloseBuySellDrawer();
    void UpdateBottomBar();

    std::unique_ptr<TMapRenderer> mapRenderer;
    TMapManager::EventListenerId  mapListener = 0;

    // The in-game menu and its dialogs (retail's panes 0x0066f748 ...).
    std::unique_ptr<TInGameMenu>  ingamemenu;
    bool menuPending = false;       // the menu opens once its thumbnail is taken

    // The player and target status bar (retail's pane 0x0065a8c0).
    std::unique_ptr<TPlyrStatusBar> statusbar;

    // The HUD's bottom bar: quick-spell rings and the belt (retail's pane
    // 0x0065b638, the drawer's content in mode 2).
    std::unique_ptr<TBottomBarPane> bottombar;

    // Mode flags
    bool fullscreen   = false;
    bool demomode     = false;
    bool controlon    = true;
    bool interfacedirty = false;
    bool multidirty   = false;

    // Game time
    int32_t gameframes        = 0;  // frames since this PlayScreen started
    int32_t sessionstart      = 0;  // frame count at last SetGameTime
    int32_t lastsessionframes = 0;  // total frames in previous game session
    int32_t gametime          = 0;  // hundredths of a second, in-game
    int32_t timeofday         = 0;  // game minutes

    // Pane plumbing
    PTPane nextpane = nullptr;

    // The play screen's fader (retail +0x5bc), set up in Initialize.
    TScreenFade screenfade;

    // `playmovie`'s movie while it plays.
    TMoviePane movie;
    bool       movieplaying = false;

    // The still behind a load during play.
    enum class EFreeze : uint8_t { None, Capturing, Frozen };
    EFreeze                       freeze = EFreeze::None;
    std::vector<uint8_t>          frozenPixels;     // the capture, until uploaded
    int32_t                       frozenWidth  = 0;
    int32_t                       frozenHeight = 0;
    TTextureHandle                frozenTexture = kInvalidTexture;
    std::unique_ptr<THudDrawable> frozenLayer;
    bool                          stillShown = false;

    // The bottom drawer (+0x6c0 mode, +0x6b8 shop request, +0x6b4 close
    // request).
    EDrawer drawer         = EDrawer::Hud;
    bool    buysellrequest = false;
    bool    drawerclose    = false;

    // Effect imagery cached at boot (blood, sparks). Optional; kept null
    // when the imagery isn't in the current data set.
    TObjectImagery* bloodimagery  = nullptr;
    TObjectImagery* sparksimagery = nullptr;
};

// The day clock: game minutes against rules.def DAYLENGTH units, a day being
// 1440 minutes (retail 0x0047eb30 / 0x0047eb50; see playscreen.cpp).
int32_t ConvertFramesToMinutes(int32_t frames);
int32_t ConvertMinutesToFrames(int32_t minutes);
